### ISSUE TITLE
Installation issue on Windows 

### ISSUE THREAD

**Issue by bdalpedri** [seriph78/COTAN#1]
Hello! 
I was trying to install COTAN on Windows, but it gave me the following error because of mine R installation folder: 
```
'\\fileserver\profiles\dalpedri\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'COTAN' ...
** using staged installation
./configure.win: line 2: //fileserver/profiles/dalpedri/My: No such file or directory
Warning in system("sh ./configure.win") : Exit code was 127
ERROR: configuration failed for package 'COTAN'
* removing '\\fileserver/profiles/dalpedri/My Documents/R/R-4.1.2/library/COTAN'
```
I solved it by cloning the repository and installing it after adding double quotes (`"${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe"`) to the R installation path in https://github.com/seriph78/COTAN/blob/7ea9d488addf651e5641052771ced4125009c151/configure.win#L2

It could be useful to fix it for other users as well (I don't know if it affects also other platforms) 
Thanks 😄

**Comment by seriph78** [comment]
Great! Thank you very much.
