### ISSUE TITLE
error in E17.5 gene clustering pipeline

### ISSUE THREAD

**Issue by mocherry** [seriph78/COTAN#11]
Dear Silvia,

when trying to follow the pipeline you describe on "https://seriph78.github.io/Cotan_paper/Gene_clustering.html"
everything works nice up to the following step:
temp.coex = as.matrix(objE17@coex[rownames(objE17@coex) %in% rownames(col.secondary),
                          colnames(objE17@coex) %in% unlist(layers)])

here I get the following error:
Error in h(simpleError(msg, call)): Error when evaluating argument 'x'  with method for function 'as.matrix' : wrong number of dimensions

Any suggestions?
Thanks and best,
Matthias

**Comment by trinetra75** [comment]
Please be aware that COTAN v. 2.0.0 is not really backward compatible with previous versions.

In particular examples the examples from this page cannot be used *as is*, but they need to be adjusted to the new commands' sintax.

An update of the examples is planned, an in the mean-time it is possible to check the *vignette* for instructions on how to use the package.
