### ISSUE TITLE
pca_1 for gene clustering missing

### ISSUE THREAD

**Issue by pavsol** [seriph78/COTAN#2]
Hi,
I am trying to follow the [workflow](https://seriph78.github.io/Cotan_paper/Gene_clustering.html) for the gene clustering according to the Cotan paper. However, I cannot figure out how to obtain `pca_1` for the line
`par_pca = pca_1[colnames(g.space)[colnames(g.space) %in% rownames(pca_1)],]`

It is not mentioned anywhere in the example. Any advice will be appreciated.

Pavel

**Comment by seriph78** [comment]
Sorry there was a part of the code missing in the documentation... I will
fix it as soon as possible... The code missing is:

hc.norm = hclust(dist(g.space), method = "ward.D2")
dend <- as.dendrogram(hc.norm)
pca_1 = as.data.frame(coex.pca.genes$rotation[,1:10])
pca_1 = pca_1[order.dendrogram(dend),]
cut = cutree(hc.norm, k = 7, order_clusters_as_data = F)
#- Next lines are only to color and plot the secondary markers
tmp = get.pval(object = objE17,gene.set.col =unlist(layers),gene.set.row =
colnames(g.space))
for (m in unlist(layers)) {
tmp = as.data.frame(tmp[order(tmp[,m]),])
tmp$rank = c(1:nrow(tmp))
colnames(tmp)[ncol(tmp)] = paste("rank",m,sep = ".")
}
rank.genes = tmp[,(length(unlist(layers))+1):ncol(tmp)]
for (c in c(1:length(colnames(rank.genes)))) {
colnames(rank.genes)[c] =strsplit(colnames(rank.genes)[c], split='.',fixed =
T)[[1]][2]
}
L1 = rowSums(rank.genes[,layers[[1]]])
L1[layers[[1]]] = 1
L2 = rowSums(rank.genes[,layers[[2]]])
L2[layers[[2]]] = 1
L4 = rowSums(rank.genes[,layers[[3]]])
L4[layers[[3]]] = 1
L5 =rowSums(rank.genes[,layers[[4]]])
L5[layers[[4]]] = 1
P = rowSums(rank.genes[,layers[[5]]])
P[layers[[5]]] = 1
col.secondary = merge(L1,L2,by="row.names",all.x=TRUE)
colnames(col.secondary)[2:3] = c("L1","L2")
rownames(col.secondary) = col.secondary$Row.names
col.secondary = col.secondary[,2:ncol(col.secondary)]
col.secondary = merge(col.secondary,L4,by="row.names",all.x=TRUE)
colnames(col.secondary)[ncol(col.secondary)] = "L4"
rownames(col.secondary) = col.secondary$Row.names
col.secondary = col.secondary[,2:ncol(col.secondary)]
col.secondary = merge(col.secondary,L5,by="row.names",all.x=TRUE)
colnames(col.secondary)[ncol(col.secondary)] = "L5"
rownames(col.secondary) = col.secondary$Row.names
col.secondary = col.secondary[,2:ncol(col.secondary)]
col.secondary = merge(col.secondary,P,by="row.names",all.x=TRUE)
colnames(col.secondary)[ncol(col.secondary)] = "P"
rownames(col.secondary) = col.secondary$Row.names
col.secondary = col.secondary[,2:ncol(col.secondary)]
# this part is to check that we will color as secondary markers only the
genes linked to the
# primary with positive coex
temp.coex = ***@***.******@***.***) %in% rownames(
col.secondary),
***@***.***) %in% unlist(layers)])
for (n in rownames(col.secondary)) {
if(any(temp.coex[n,c("Reln","Lhx5")] < 0)){
col.secondary[n,"L1"] = 100000
}
if(any(temp.coex[n,c("Cux1","Satb2")] < 0)){
col.secondary[n,"L2"] = 100000
}
if(any(temp.coex[n,c("Rorb","Sox5")] < 0)){
col.secondary[n,"L4"] = 100000
}
if(any(temp.coex[n,c("Bcl11b","Fezf2")] < 0)){
col.secondary[n,"L5"] = 100000
}
if(any(temp.coex[n,c("Vim","Hes1")] < 0)){
col.secondary[n,"P"] = 100000
}
}
mylist.names <- c("L1", "L2", "L4","L5","P")
pos.link <- vector("list", length(mylist.names))
names(pos.link) <- mylist.names
for (g in rownames(col.secondary)) {
if(length( which(col.secondary[g,] == min(col.secondary[g,]))) == 1 ){
pos.link[[which(col.secondary[g,] == min(col.secondary[g,])) ]] =
c(pos.link[[which(col.secondary[g,] == min(col.secondary[g,])) ]], g)
}
}
# ----
pca_1$highlight = with(pca_1,
ifelse(rownames(pca_1) %in% pos.link$L5, "genes related to L5/6",
ifelse(rownames(pca_1) %in% pos.link$L2 , "genes related to L2/3",
ifelse(rownames(pca_1) %in% pos.link$P , "genes related to Prog" ,
ifelse(rownames(pca_1) %in% pos.link$L1 , "genes related to L1" ,
ifelse(rownames(pca_1) %in% pos.link$L4 ,"genes related to L4" ,
"not marked"))))))
# But sort them based on their order in dend:
#colors_to_use <- pca_1$highlight[order.dendrogram(dend)]
#mycolours <- c("genes related to L5/6" = "#3C5488FF","genes related to
L2/3"="#F39B7FFF","genes related to Prog"="#4DBBD5FF","genes related to
L1"="#E64B35FF","genes related to L4" = "#91D1C2FF", "not
marked"="#B09C85FF")
pca_1$hclust = cut
pca_1$colors = NA
pca_1[pca_1$highlight == "genes related to L5/6", "colors"] = "#3C5488FF"
pca_1[pca_1$highlight == "genes related to L2/3","colors"] = "#F39B7FFF"
pca_1[pca_1$highlight == "genes related to Prog","colors"] = "#4DBBD5FF"
pca_1[pca_1$highlight == "genes related to L1","colors"] = "#E64B35FF"
pca_1[pca_1$highlight == "genes related to L4","colors"] = "#91D1C2FF"
pca_1[pca_1$highlight == "not marked","colors"] = "#B09C85FF"
dend =branches_color(dend,k=7,col=c("#4DBBD5FF","#91D1C2FF","#E64B35FF","
gray80","#3C5488FF","#F39B7FFF","gray80" ),groupLabels = T)
dend =color_labels(dend,k=7,labels = rownames(pca_1),col=pca_1$colors)
dend %>%
dendextend::set("labels", ifelse(labels(dend) %in% rownames(pca_1)[rownames(
pca_1) %in% colnames(g.space)] ,labels(dend),"")) %>%
# set("branches_k_color", value = c("gray80","#4DBBD5FF","#91D1C2FF"
,"gray80","#F39B7FFF","#E64B35FF","#3C5488FF"), k = 7) %>%
plot(horiz=F, axes=T,ylim = c(0,80))

cluster = cut
cluster[cluster == 1] = "#4DBBD5FF"
cluster[cluster == 2] = "#91D1C2FF"
cluster[cluster == 3] = "#E64B35FF"
cluster[cluster == 4] = "#B09C85FF"
cluster[cluster == 5] = "#3C5488FF"
cluster[cluster == 6] = "#F39B7FFF"
cluster[cluster == 7] = "#B09C85FF"
plot.new()
plot(dend,horiz=T, axes=T,xlim = c(100,0),leaflab = "none")
abline(v = 47, lty = 2)
colored_bars(cluster,dend,horiz = T,sort_by_labels_order = F,y_shift = 1,
rowLabels= "" )
gridGraphics::grid.echo()
tree <- grid.grab()

Best regards

-- 
*Silvia Giulia Galfrè *
