### ISSUE TITLE
Revdep check

### ISSUE THREAD

**Issue by rsbivand** [seriph78/COTAN#49]
Errors with current `Matrix`: 
[00check.log](https://github.com/seriph78/COTAN/files/13486102/00check.log)

**Comment by trinetra75** [comment]
The issue stems from a change in the `Matrix` package not yet reflected in the `irlba` package `COTAN` depends on.
Issue has been fixed, but in case a possible solution/workaround is to uninstall and reinstall the `irlba` package.
