### ISSUE TITLE
error in clean function

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [seriph78/COTAN#6]
Hello,

I get the following error when I use the clean function

```
> ttm = clean(obj)
[1] "Start estimation mu with linear method"
[1] 13177  9942
Error in py_run_file_impl(file, local, convert) :
  AttributeError: module 'pandas' has no attribute 'plotting'
```

Is there an other way to proceed to the calculation of the COEX values? I have already remover cell contaminats and dead cells in Seurat.

Thanks a lot,
Christoforos

**Comment by seriph78** [comment]
Ok, I will check. Can you tell me a little bit more about the architecture you are using and the loaded packages?

**Comment by seriph78** [comment]
We have recently updated the code with major improvements… We also removed all dependencies from Python. The new release will be available on Bioconductor soon but you can try the new code from GitHub in the meantime. Please let me know if you encounter any issues.

Best wishes
