### ISSUE TITLE
hclust(dist_cells, method = "complete") : size cannot be na nor exceed 65536

### ISSUE THREAD

**Issue by zhouqz** [seriph78/COTAN#7]
The dataset is 197721*28727. The error happens in clean.

Error:
hclust(dist_cells, method = "complete") : size cannot be na nor exceed 65536. Any suggestions?

Thanks & Best,
QZ

**Comment by seriph78** [comment]
We have recently updated the code with significant improvements. It will be available on Bioconductor soon but, in the meantime, you can try the new code from GitHub. Please let me know if you encounter any issues.

Best wishes
