### ISSUE TITLE
trying Cotan with dataset

### ISSUE THREAD

**Issue by mocherry** [seriph78/COTAN#8]
Dear COTAN developers,

I would like to try COTAN, but fail already at the beginning.
I wanted to follow the  P0 dentate gyrus from https://seriph78.github.io/Cotan_paper/P0_dentate_gyrus_analysis.html.
Could you please tell me where I get the data file: separation_age/P0.csv?

Thanks a lot and best,
Matthias

**Comment by seriph78** [comment]
Thank you for your interest! To reconstruct each age, you can use the GSE104323_metadata_barcodes_24185cells.txt.gz file (you can use the "age" column), which is available at https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE104323. The entire dataset expression file (GSE104323_10X_expression_data_V2.tab.gz) is also available on the same website. 

Best regards
