### ISSUE TITLE
ttm = clean(obj) gives an error???

### ISSUE THREAD

**Issue by mocherry** [seriph78/COTAN#9]
Dear all,

I just had another error when trying to run the P0 dentate gyrus example pipeline. 
when calling ttm = clean(obj) 
I get:

Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : 
  no  'dimnames[[.]]': character indexing cannot be used

I guess much has to do with me being so in experienced with R.

Zhanks for any help.
best,
Matthias

**Comment by seriph78** [comment]
We have recently updated the code with significant improvements… it will be available on Bioconductor soon but, in the meantime, you can try the new code from GitHub. Please let me know if you encounter any issues.

Best wishes
